### ISSUE TITLE
KSP 1.9.x resets resources to prefab while cloning parts

### ISSUE THREAD

**Issue by ferox96** [net-lisias-ksp/KSP-Recall#1] opened 2020-02-26 03:13 UTC
Tried updating to 1.9 since most mods behave reasonably on updates nowadays.  Began noticing some parts drifting each time I loaded my craft (either in flight or VAB).  Seems any parts that have been tweaked start to wander when loading.

Also noticed that when copying a part that had been altered, the new part retained the correct appearance and size, but was given the default values for the original part.  (FL-T400 tank scaled to 3.75 has almost 2k LOx, copy has 360).  Tweakscale seems to be applying itself at the wrong time or somehow affecting the "assembly order" upon load in.  The most interesting fact is that if I load a craft and a part wanders, then reload the same craft without saving, the part will have wandered farther than before.

I am using other mods such as mechjeb, but afaik none would be interfering with TS or craft loading.  Hope I have been of some service, TS has been very nice to me, would like to return the favor.

**Comment by Lisias** [comment] 2020-03-01 08:43
This issue was transfered to KSP-Recall, as this is where the problem will be handled.

**Comment by Lisias** [comment] 2020-03-01 15:21
> Gotta say again that i'm so appreciative of the effort you have put into this issue. I know i'm not alone in the struggle but I don't take it for granted.

Welcome! :)


> ....upon entering my GameData folder, I am noticing I do not have .configcache or .configSHA. Is this an issue?

Yes. It means that or you are risking your SAS using my Experimental MM fork :D , or you are using the Stock MM but there're errors on the patches, what prevents MM to built the cache.

This **can** be a reason for the wandering parts - what you describes happens when TweakScale is borking due a NRE in its guts what just happens by third-parties code injecting non-sense on the GameDatabase (or borking themselves when called by TweakScale when they implement the Scale_Redist interface) - and I just inadvertently (re)confirmed this while writing KSP Recall, by the way. :)

Right now, you need to ask for help on the MM thread - what historically ended up with the user coming back here, as they were not helpful.  :P 

But since today I'm busy with this new Recall stunt, may I ask you to ask for help there first? Sometimes someone helps, and if by the end of the day you still have the problem, ping me back here with the most recent copy of your KSL.Log and also the MM logs (I think they are in the `<ksp_root>/Logs` directory) and I will give it a look.

**Comment by Lisias** [comment] 2020-03-02 02:28
@ferox96 , I think you will want to keep an eye on issue #3 .

**Comment by Lisias** [comment] 2020-03-02 02:31
This feature is working fine - apparently. :)

Closing it for publishing a new release.

**Closed by Lisias** 2020-03-02 02:31 UTC
