### ISSUE TITLE
Kerbal going on EVA on Kerbin without helmet instantly dies

### ISSUE THREAD

**Issue by BTAxis** [net-lisias-ksp/KSP-Recall#26] opened 2021-07-27 14:54 UTC
The Kerbal will die because it's "too cold". It only seems to occur right when exiting the pod if the Kerbal isn't wearing a helmet, or when removing the helmet while still holding on to the hatch.

There seems to be nothing in the log that sheds light on why this happens, but I'm confident it is caused by Recall 2.0.3 (obtained from CKAN). I can reproduce with this mod and nothing else. Removing Recall from my otherwise heavily modded setup makes the bug go away.

**Comment by Lisias** [comment] 2021-09-04 09:43
Hi, @BTAxis . Sorry being **SO LATE** on the answer - usually people kick me in Forum too, so I ended up missing this one. Sorry again.

Yes, what you describes appears to be a undesired collateral side effect of `ChillingOut`, that by the way is also messing up KSPIE (see issue #25 ).

I will work on a fix ASAP.

**Comment by Lisias** [comment] 2021-09-07 22:03
I think I found the cause. I ended up applying ChillingOut everywhere, and completely forgot I should not apply this patch on Kerbals.

Additionally, using 0 to initialise the part's temperature was a less than happy decision, as 0 is 0 Kelvin (-273ºC).

So both this mishaps, once applied to a Kerbal, leaded to the disaster.

Fixing it.

**Comment by Lisias** [comment] 2021-09-07 22:33
Fixed on commit https://github.com/net-lisias-ksp/KSP-Recall/commit/deb8eb23949ee82d02d2aab598a04330c9ca9ea2

**Closed by Lisias** 2021-09-07 22:33 UTC
